
// Marcel Timm, RhinoDevel, 2020nov30

/** To be run during page load to augment single global obj. with new property.
 */
(function() // IIFE
{
    'use strict';
    
    // Requirements:
    //
    var flagAffect = rhino6502doc.flagAffect;

    /** 6502 commands array.
     * 
     *  - Commands are ordered by mnemonic (also see mnemonics array),
     *    followed by address mode ID (where the address mode ID's first
     *    character equals the byte count).
     */
    rhino6502doc.commands = [
        {
            opCode: 105,
            mnemonic: 'ADC',
            addrModeId: '21',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A + *addr + C;'
        },
        {
            opCode: 101,
            mnemonic: 'ADC',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A + *addr + C;'
        },
        {
            opCode: 117,
            mnemonic: 'ADC',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A + *addr + C;'
        },
        {
            opCode: 97,
            mnemonic: 'ADC',
            addrModeId: '26',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A + *addr + C;'
        },
        {
            opCode: 113,
            mnemonic: 'ADC',
            addrModeId: '27',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 5,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A + *addr + C;'
        },
        {
            opCode: 109,
            mnemonic: 'ADC',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A + *addr + C;'
        },
        {
            opCode: 125,
            mnemonic: 'ADC',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A + *addr + C;'
        },
        {
            opCode: 121,
            mnemonic: 'ADC',
            addrModeId: '33',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A + *addr + C;'
        },
        {
            opCode: 41,
            mnemonic: 'AND',
            addrModeId: '21',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A & val'
        },
        {
            opCode: 37,
            mnemonic: 'AND',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A & *mem'
        },
        {
            opCode: 53,
            mnemonic: 'AND',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A & *mem'
        },
        {
            opCode: 33,
            mnemonic: 'AND',
            addrModeId: '26',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A & *mem'
        },
        {
            opCode: 49,
            mnemonic: 'AND',
            addrModeId: '27',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 5,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A & *mem'
        },
        {
            opCode: 45,
            mnemonic: 'AND',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A & *mem'
        },
        {
            opCode: 61,
            mnemonic: 'AND',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A & *mem'
        },
        {
            opCode: 57,
            mnemonic: 'AND',
            addrModeId: '33',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A & *mem'
        },
        {
            opCode: 10,
            mnemonic: 'ASL',
            addrModeId: '12',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A << 1'
        },
        {
            opCode: 6,
            mnemonic: 'ASL',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 5,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem << 1'
        },
        {
            opCode: 22,
            mnemonic: 'ASL',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem << 1'
        },
        {
            opCode: 14,
            mnemonic: 'ASL',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem << 1'
        },
        {
            opCode: 30,
            mnemonic: 'ASL',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 7,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem << 1'
        },
        {
            opCode: 144,
            mnemonic: 'BCC',
            addrModeId: '22',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: true,
            codeEquiv: ''
        },
        {
            opCode: 176,
            mnemonic: 'BCS',
            addrModeId: '22',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: true,
            codeEquiv: ''
        },
        {
            opCode: 240,
            mnemonic: 'BEQ',
            addrModeId: '22',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: true,
            codeEquiv: ''
        },
        {
            opCode: 36,
            mnemonic: 'BIT',
            addrModeId: '23',
            n: flagAffect.bitSeven,
            v: flagAffect.bitSix,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 44,
            mnemonic: 'BIT',
            addrModeId: '31',
            n: flagAffect.bitSeven,
            v: flagAffect.bitSix,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 48,
            mnemonic: 'BMI',
            addrModeId: '22',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: true,
            codeEquiv: ''
        },
        {
            opCode: 208,
            mnemonic: 'BNE',
            addrModeId: '22',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: true,
            codeEquiv: ''
        },
        {
            opCode: 16,
            mnemonic: 'BPL',
            addrModeId: '22',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: true,
            codeEquiv: ''
        },
        {
            opCode: 0,
            mnemonic: 'BRK',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.one,
            d: flagAffect.none,
            i: flagAffect.some,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 7,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 80,
            mnemonic: 'BVC',
            addrModeId: '22',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: true,
            codeEquiv: ''
        },
        {
            opCode: 112,
            mnemonic: 'BVS',
            addrModeId: '22',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: true,
            codeEquiv: ''
        },
        {
            opCode: 24,
            mnemonic: 'CLC',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.zero,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'C = 0'
        },
        {
            opCode: 216,
            mnemonic: 'CLD',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.zero,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'D = 0'
        },
        {
            opCode: 88,
            mnemonic: 'CLI',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.zero,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'I = 0'
        },
        {
            opCode: 184,
            mnemonic: 'CLV',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.zero,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'V = 0'
        },
        {
            opCode: 201,
            mnemonic: 'CMP',
            addrModeId: '21',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 197,
            mnemonic: 'CMP',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 213,
            mnemonic: 'CMP',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 193,
            mnemonic: 'CMP',
            addrModeId: '26',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 209,
            mnemonic: 'CMP',
            addrModeId: '27',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 5,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 205,
            mnemonic: 'CMP',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 221,
            mnemonic: 'CMP',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 217,
            mnemonic: 'CMP',
            addrModeId: '33',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 224,
            mnemonic: 'CPX',
            addrModeId: '21',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 228,
            mnemonic: 'CPX',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 236,
            mnemonic: 'CPX',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 192,
            mnemonic: 'CPY',
            addrModeId: '21',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 196,
            mnemonic: 'CPY',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 204,
            mnemonic: 'CPY',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 198,
            mnemonic: 'DEC',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 5,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem - 1'
        },
        {
            opCode: 214,
            mnemonic: 'DEC',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem - 1'
        },
        {
            opCode: 206,
            mnemonic: 'DEC',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem - 1'
        },
        {
            opCode: 222,
            mnemonic: 'DEC',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 7,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem - 1'
        },
        {
            opCode: 202,
            mnemonic: 'DEX',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'X = X - 1'
        },
        {
            opCode: 136,
            mnemonic: 'DEY',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'Y = Y - 1'
        },
        {
            opCode: 73,
            mnemonic: 'EOR',
            addrModeId: '21',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A ^ val'
        },
        {
            opCode: 69,
            mnemonic: 'EOR',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A ^ *mem'
        },
        {
            opCode: 85,
            mnemonic: 'EOR',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A ^ *mem'
        },
        {
            opCode: 65,
            mnemonic: 'EOR',
            addrModeId: '26',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A ^ *mem'
        },
        {
            opCode: 81,
            mnemonic: 'EOR',
            addrModeId: '27',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 5,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A ^ *mem'
        },
        {
            opCode: 77,
            mnemonic: 'EOR',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A ^ *mem'
        },
        {
            opCode: 93,
            mnemonic: 'EOR',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A ^ *mem'
        },
        {
            opCode: 89,
            mnemonic: 'EOR',
            addrModeId: '33',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A ^ *mem'
        },
        {
            opCode: 230,
            mnemonic: 'INC',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 5,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem + 1'
        },
        {
            opCode: 246,
            mnemonic: 'INC',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem + 1'
        },
        {
            opCode: 238,
            mnemonic: 'INC',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem + 1'
        },
        {
            opCode: 254,
            mnemonic: 'INC',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 7,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem + 1'
        },
        {
            opCode: 232,
            mnemonic: 'INX',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'X = X + 1'
        },
        {
            opCode: 200,
            mnemonic: 'INY',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'Y = Y + 1'
        },
        {
            opCode: 76,
            mnemonic: 'JMP',
            addrModeId: '31',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 108,
            mnemonic: 'JMP',
            addrModeId: '34',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 32,
            mnemonic: 'JSR',
            addrModeId: '31',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 169,
            mnemonic: 'LDA',
            addrModeId: '21',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = val'
        },
        {
            opCode: 165,
            mnemonic: 'LDA',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = *mem'
        },
        {
            opCode: 181,
            mnemonic: 'LDA',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = *mem'
        },
        {
            opCode: 161,
            mnemonic: 'LDA',
            addrModeId: '26',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = *mem'
        },
        {
            opCode: 177,
            mnemonic: 'LDA',
            addrModeId: '27',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 5,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = *mem'
        },
        {
            opCode: 173,
            mnemonic: 'LDA',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = *mem'
        },
        {
            opCode: 189,
            mnemonic: 'LDA',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = *mem'
        },
        {
            opCode: 185,
            mnemonic: 'LDA',
            addrModeId: '33',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = *mem'
        },
        {
            opCode: 162,
            mnemonic: 'LDX',
            addrModeId: '21',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'X = val'
        },
        {
            opCode: 166,
            mnemonic: 'LDX',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'X = *mem'
        },
        {
            opCode: 182,
            mnemonic: 'LDX',
            addrModeId: '25',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'X = *mem'
        },
        {
            opCode: 174,
            mnemonic: 'LDX',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'X = *mem'
        },
        {
            opCode: 190,
            mnemonic: 'LDX',
            addrModeId: '33',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'X = *mem'
        },
        {
            opCode: 160,
            mnemonic: 'LDY',
            addrModeId: '21',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'Y = val'
        },
        {
            opCode: 164,
            mnemonic: 'LDY',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'Y = *mem'
        },
        {
            opCode: 180,
            mnemonic: 'LDY',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'Y = *mem'
        },
        {
            opCode: 172,
            mnemonic: 'LDY',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'Y = *mem'
        },
        {
            opCode: 188,
            mnemonic: 'LDY',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'Y = *mem'
        },
        {
            opCode: 74,
            mnemonic: 'LSR',
            addrModeId: '12',
            n: flagAffect.zero,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A >> 1'
        },
        {
            opCode: 70,
            mnemonic: 'LSR',
            addrModeId: '23',
            n: flagAffect.zero,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 5,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem >> 1'
        },
        {
            opCode: 86,
            mnemonic: 'LSR',
            addrModeId: '24',
            n: flagAffect.zero,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem >> 1'
        },
        {
            opCode: 78,
            mnemonic: 'LSR',
            addrModeId: '31',
            n: flagAffect.zero,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem >> 1'
        },
        {
            opCode: 94,
            mnemonic: 'LSR',
            addrModeId: '32',
            n: flagAffect.zero,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 7,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = *mem >> 1'
        },
        {
            opCode: 234,
            mnemonic: 'NOP',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 9,
            mnemonic: 'ORA',
            addrModeId: '21',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A | val'
        },
        {
            opCode: 5,
            mnemonic: 'ORA',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A | *mem'
        },
        {
            opCode: 21,
            mnemonic: 'ORA',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A | *mem'
        },
        {
            opCode: 1,
            mnemonic: 'ORA',
            addrModeId: '26',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A | *mem'
        },
        {
            opCode: 17,
            mnemonic: 'ORA',
            addrModeId: '27',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 5,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A | *mem'
        },
        {
            opCode: 13,
            mnemonic: 'ORA',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A | *mem'
        },
        {
            opCode: 29,
            mnemonic: 'ORA',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A | *mem'
        },
        {
            opCode: 25,
            mnemonic: 'ORA',
            addrModeId: '33',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A | *mem'
        },
        {
            opCode: 72,
            mnemonic: 'PHA',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 8,
            mnemonic: 'PHP',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 104,
            mnemonic: 'PLA',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 40,
            mnemonic: 'PLP',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.some,
            d: flagAffect.some,
            i: flagAffect.some,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 42,
            mnemonic: 'ROL',
            addrModeId: '12',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 38,
            mnemonic: 'ROL',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 5,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 54,
            mnemonic: 'ROL',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 46,
            mnemonic: 'ROL',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 62,
            mnemonic: 'ROL',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 7,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 106,
            mnemonic: 'ROR',
            addrModeId: '12',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 102,
            mnemonic: 'ROR',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 5,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 118,
            mnemonic: 'ROR',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 110,
            mnemonic: 'ROR',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 126,
            mnemonic: 'ROR',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 7,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 64,
            mnemonic: 'RTI',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.some,
            d: flagAffect.some,
            i: flagAffect.some,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 96,
            mnemonic: 'RTS',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 233,
            mnemonic: 'SBC',
            addrModeId: '21',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A - val - 1 + C'
        },
        {
            opCode: 229,
            mnemonic: 'SBC',
            addrModeId: '23',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A - *mem - 1 + C'
        },
        {
            opCode: 245,
            mnemonic: 'SBC',
            addrModeId: '24',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A - *mem - 1 + C'
        },
        {
            opCode: 225,
            mnemonic: 'SBC',
            addrModeId: '26',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A - *mem - 1 + C'
        },
        {
            opCode: 241,
            mnemonic: 'SBC',
            addrModeId: '27',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 5,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A - *mem - 1 + C'
        },
        {
            opCode: 237,
            mnemonic: 'SBC',
            addrModeId: '31',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A - *mem - 1 + C'
        },
        {
            opCode: 253,
            mnemonic: 'SBC',
            addrModeId: '32',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A - *mem - 1 + C'
        },
        {
            opCode: 249,
            mnemonic: 'SBC',
            addrModeId: '33',
            n: flagAffect.some,
            v: flagAffect.some,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.some,
            cycleCountMin: 4,
            cycleAddOnPageCross: true,
            cycleAddOnBranch: false,
            codeEquiv: 'A = A - *mem - 1 + C'
        },
        {
            opCode: 56,
            mnemonic: 'SEC',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.one,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'C = 1'
        },
        {
            opCode: 248,
            mnemonic: 'SED',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.one,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'D = 1'
        },
        {
            opCode: 120,
            mnemonic: 'SEI',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.one,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'I = 1'
        },
        {
            opCode: 133,
            mnemonic: 'STA',
            addrModeId: '23',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = A'
        },
        {
            opCode: 149,
            mnemonic: 'STA',
            addrModeId: '24',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = A'
        },
        {
            opCode: 129,
            mnemonic: 'STA',
            addrModeId: '26',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = A'
        },
        {
            opCode: 145,
            mnemonic: 'STA',
            addrModeId: '27',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 6,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = A'
        },
        {
            opCode: 141,
            mnemonic: 'STA',
            addrModeId: '31',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = A'
        },
        {
            opCode: 157,
            mnemonic: 'STA',
            addrModeId: '32',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 5,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = A'
        },
        {
            opCode: 153,
            mnemonic: 'STA',
            addrModeId: '33',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 5,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = A'
        },
        {
            opCode: 134,
            mnemonic: 'STX',
            addrModeId: '23',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = X'
        },
        {
            opCode: 150,
            mnemonic: 'STX',
            addrModeId: '25',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = X'
        },
        {
            opCode: 142,
            mnemonic: 'STX',
            addrModeId: '31',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = X'
        },
        {
            opCode: 132,
            mnemonic: 'STY',
            addrModeId: '23',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 3,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = Y'
        },
        {
            opCode: 148,
            mnemonic: 'STY',
            addrModeId: '24',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = Y'
        },
        {
            opCode: 140,
            mnemonic: 'STY',
            addrModeId: '31',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 4,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: '*mem = Y'
        },
        {
            opCode: 170,
            mnemonic: 'TAX',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'X = A'
        },
        {
            opCode: 168,
            mnemonic: 'TAY',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'Y = A'
        },
        {
            opCode: 186,
            mnemonic: 'TSX',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 138,
            mnemonic: 'TXA',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = X'
        },
        {
            opCode: 154,
            mnemonic: 'TXS',
            addrModeId: '11',
            n: flagAffect.none,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.none,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: ''
        },
        {
            opCode: 152,
            mnemonic: 'TYA',
            addrModeId: '11',
            n: flagAffect.some,
            v: flagAffect.none,
            b: flagAffect.none,
            d: flagAffect.none,
            i: flagAffect.none,
            z: flagAffect.some,
            c: flagAffect.none,
            cycleCountMin: 2,
            cycleAddOnPageCross: false,
            cycleAddOnBranch: false,
            codeEquiv: 'A = Y'
        }
    ];
}());
